### ISSUE TITLE
运行iftoc的ruby报错

### ISSUE THREAD

**Issue by manajay** [panghaijiao/iftoc#1]
/usr/local/lib/ruby/gems/2.4.0/gems/iftoc-0.1.9/lib/iftoc.rb:11:in `parseSVGFontName': undefined method `elements' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/iftoc-0.1.9/bin/iftoc:53:in `<top (required)>'
	from /usr/local/bin/iftoc:22:in `load'
	from /usr/local/bin/iftoc:22:in `<main>'

**Comment by manajay** [comment]
manajay:Desktop manajay$ iftoc iconfont.svg -o ~/Desktop/ -l swift

**Comment by panghaijiao** [comment]
用css文件试试，然后能把你的svg文件发给我看看嘛

**Comment by manajay** [comment]
我是直接用sketch生成的 svg文件,昨天看了你的微博,打算试试,
这个错误 是因为我设置了的字体,又将文字路径化了吗
文件链接 http://pan.baidu.com/share/link?shareid=1897447012&uk=2837400720

**Comment by panghaijiao** [comment]
目前主要适配了网站  http://www.iconfont.cn  生成的svg或css文件，针对sketch生成的svg还需要适配，sketch能生成css文件嘛，有的话也发给我，谢谢，我都一起适配，适配好告诉你！

**Comment by panghaijiao** [comment]
朋友，你这个文件跟我想的还不同，能加我QQ吗？275742376，跟你详细沟通！

**Comment by panghaijiao** [comment]
感谢反馈，经过沟通，sketch导出的只是单个svg矢量图，并没有字体信息，需要上传到http://www.iconfont.cn/ 下载后才有iconfont.ttf以及iconfont.svg或iconfont.css文件，使用iconfont.svg或iconfont.css文件才能生成iconfont代码

**Comment by manajay** [comment]
嗯 好的
